TAP version 13
    # Subtest: t.end()
    ok 1 - did not timeout
    not ok 2 - timeout!
      ---
      {"at":{"column":3,"file":"test/test/sync-timeout.js","line":15},"expired":"t.end()","source":"t.test('t.end()', opt, function (t) {\n","timeout":50}
      ...
    1..2
    # failed 1 of 2 tests
not ok 1 - t.end() ___/# time=[0-9.]+(ms)?/~~~
  ---
  {"at":{"column":3,"file":"test/test/sync-timeout.js","line":15},"results":{"count":2,"fail":1,"ok":false,"pass":1,"plan":{"end":2,"start":1}},"source":"t.test('t.end()', opt, function (t) {\n","timeout":50}
  ...

    # failed 1 of 2 tests
    # Subtest: plan()
    1..1
    ok 1 - did not time out
not ok 2 - plan() ___/# time=[0-9.]+(ms)?/~~~
  ---
  {"at":{"column":3,"file":"test/test/sync-timeout.js","line":15},"error":"test count exceeds plan","results":{"count":1,"ok":false,"pass":1,"plan":{"end":1,"start":1}},"source":"t.test('t.end()', opt, function (t) {\n","timeout":50}
  ...

not ok 3 - Error: test count exceeds plan
  ---
  {"count":2,"message":"Error: test count exceeds plan","plan":1,"test":"plan()"}
  ...
1..3
# failed 3 of 3 tests
___/# time=[0-9.]+(ms)?/~~~

